# Generated by Django 5.0.3 on 2026-09-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_security_hardening_indexes_validators"),
        ("jobs", "0007_department_job_is_archived_job_slots_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_users",
                to="jobs.department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HR", "HR Manager"),
                    ("APPLICANT", "Applicant"),
                    ("DEPARTMENT", "Department User"),
                ],
                db_index=True,
                default="APPLICANT",
                max_length=20,
            ),
        ),
    ]
