# Generated by Django 5.0.3 on 2026-09-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_user_department_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HR", "HR Manager"),
                    ("APPLICANT", "Applicant"),
                    ("DEPARTMENT_DIRECTOR", "Department Director"),
                    ("DEPARTMENT", "Department User"),
                ],
                db_index=True,
                default="APPLICANT",
                max_length=30,
            ),
        ),
    ]
