# Generated by Django 5.0.3 on 2026-09-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="grade_award",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="institution_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="qualification",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("NATIONAL_ID", "National ID"),
                    ("RESUME", "Resume/CV"),
                    ("COVER_LETTER", "Cover Letter"),
                    ("INSTITUTION_INTRO", "Introduction Letter from Institution"),
                    ("STUDENT_INSURANCE", "Student Insurance Cover"),
                    ("STUDENT_ID", "Copy of Student ID"),
                    ("NEXT_OF_KIN_ID", "Copy of Next of Kin (ID & Phone)"),
                    ("KRA_PIN", "KRA PIN Certificate"),
                    ("PASSPORT_PHOTOS", "Two Colour Passport Photos (PDF)"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
