# Generated by Django 5.0.3 on 2026-09-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_profile_field_of_study_profile_grade_award_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="next_of_kin_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="next_of_kin_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
