# Generated by Django 5.0.3 on 2026-09-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_user_must_change_password_auditlog_systemsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="next_of_kin_address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="next_of_kin_relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
