# Generated by Django 5.0.3 on 2026-09-24 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_add_reviewed_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="slots_required",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Clearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("PENDING_HR_REVIEW", "Pending HR Review"),
                            ("CLEARED", "Cleared"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=25,
                    ),
                ),
                ("user_confirmed", models.BooleanField(default=False)),
                ("user_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("user_notes", models.TextField(blank=True)),
                (
                    "final_report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="clearance_docs/"
                    ),
                ),
                ("hr_cleared", models.BooleanField(default=False)),
                ("hr_cleared_at", models.DateTimeField(blank=True, null=True)),
                ("hr_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearance",
                        to="jobs.application",
                    ),
                ),
                (
                    "hr_cleared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleared_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="jobs.department",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("JOB_POSTED", "Job Posted"),
                            ("CLEARANCE_UPDATE", "Clearance Update"),
                            ("APPLICATION_UPDATE", "Application Update"),
                            ("GENERAL", "General Notification"),
                        ],
                        default="JOB_POSTED",
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="jobs.department",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
