# Generated by Django 5.0.3 on 2026-09-24 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_department_job_is_archived_job_slots_required_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-applied_at"]},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="clearance",
            name="department_cleared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clearance",
            name="department_cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clearance",
            name="department_cleared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department_cleared_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clearance",
            name="department_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="clearance",
            name="application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clearance",
                to="jobs.application",
            ),
        ),
        migrations.AlterField(
            model_name="clearance",
            name="hr_cleared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_cleared_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clearance",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("PENDING_DEPARTMENT", "Pending Department Review"),
                    ("PENDING_HR", "Pending HR Review"),
                    ("CLEARED", "Cleared"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="NOT_STARTED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("JOB_POSTED", "Job Posted"),
                    ("CLEARANCE_UPDATE", "Clearance Update"),
                    ("APPLICATION_UPDATE", "Application Update"),
                    ("DEPLOYMENT_UPDATE", "Deployment Update"),
                    ("GENERAL", "General Notification"),
                ],
                default="JOB_POSTED",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("planned_end_date", models.DateField()),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_DEPLOYMENT", "Pending Deployment"),
                            ("DEPLOYED", "Deployed"),
                            ("EXITED", "Exited"),
                        ],
                        db_index=True,
                        default="DEPLOYED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment",
                        to="jobs.application",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_deployments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployments",
                        to="jobs.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="clearance",
            name="deployment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clearance",
                to="jobs.deployment",
            ),
        ),
        migrations.CreateModel(
            name="RecommendationLetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_letter_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rendered_content", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="recommendations/"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_letters",
                        to="jobs.deployment",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.recommendationlettertemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
