# Generated by Django 5.0.3 on 2026-09-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0009_department_contact_phone_department_director_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("ATTACHMENT", "Industrial Attachment")],
                db_index=True,
                default="ATTACHMENT",
                max_length=20,
            ),
        ),
    ]
