# Generated by Django 5.0.3 on 2026-09-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_eligibilitysetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="duration_weeks",
            field=models.PositiveIntegerField(default=12),
        ),
    ]
