# Generated by Django 5.0.3 on 2026-09-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0013_application_archived_at_application_archived_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clearance",
            name="final_report_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilitysetting",
            name="general_statement",
            field=models.TextField(
                default="Applicants must be currently enrolled undergraduate or diploma students at an accredited tertiary institution seeking mandatory industrial attachment."
            ),
        ),
    ]
