# Generated by Django 5.0.3 on 2026-09-25 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0014_clearance_final_report_submitted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="outcome_notified_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="outcome_notified_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "-applied_at"], name="jobs_applic_status_ee8cc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["job", "status"], name="jobs_applic_job_id_a25382_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clearance",
            index=models.Index(
                fields=["status", "department_cleared", "hr_cleared"],
                name="jobs_cleara_status_7865fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(
                fields=["department", "status"], name="jobs_deploy_departm_5f29ff_idx"
            ),
        ),
    ]
