# Generated by Django 5.0.3 on 2026-09-26 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0015_application_outcome_notified_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eligibilitysetting",
            name="general_statement",
            field=models.TextField(
                default="<p>Applicants must be currently enrolled undergraduate or diploma students at an accredited tertiary institution seeking mandatory industrial attachment.</p>"
            ),
        ),
        migrations.CreateModel(
            name="AtsScoringConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exceptional_min",
                    models.DecimalField(decimal_places=2, default=90.0, max_digits=5),
                ),
                (
                    "highly_qualified_min",
                    models.DecimalField(decimal_places=2, default=75.0, max_digits=5),
                ),
                (
                    "qualified_min",
                    models.DecimalField(decimal_places=2, default=60.0, max_digits=5),
                ),
                (
                    "average_min",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "qualification_benchmark",
                    models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_ats_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ATS Scoring Configuration",
                "verbose_name_plural": "ATS Scoring Configurations",
            },
        ),
    ]
