# Generated by Django 5.0.3 on 2026-09-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0018_seed_formatted_eligibility_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eligibilitysetting",
            name="general_statement",
            field=models.TextField(
                default="<h3>Who is eligible to apply</h3><p>Applicants must be <strong>currently enrolled</strong> as an undergraduate or diploma student at an <em>accredited tertiary institution</em>, seeking a mandatory industrial attachment as part of their programme requirements.</p><h3>Core eligibility requirements</h3><ul><li>Enrolment in a recognised undergraduate or diploma programme at an accredited institution</li><li>At least <strong>six months</strong> remaining before the expected graduation date</li><li>All <strong>nine required verification documents</strong> uploaded and verified on your profile</li><li>Availability for the full attachment duration advertised by the hosting department</li><li>No prior industrial attachment already completed for the same qualification</li></ul><h3>How to apply</h3><ol><li>Complete your biodata and upload every required document.</li><li>Browse the <strong>Available Attachment Positions</strong> section and select a vacancy.</li><li>Submit your application and track its status from your dashboard.</li><li>Attend any departmental screening or interview that is arranged.</li></ol><p>Only applicants who satisfy the criteria above are considered. For questions about eligibility, contact the Human Resource Directorate.</p>"
            ),
        ),
    ]
