# Generated by Django 5.0.3 on 2026-09-28 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_status_history(apps, schema_editor):
    """
    Give pre-existing applications a starting point in the new timeline.

    Without this, every application created before this migration would show an
    empty history to the applicant, which reads as "nothing happened yet" for
    applications that may already have been decided and deployed.

    The timestamps that genuinely exist are reused rather than invented:

      * every application gets a "submitted" event at its real ``applied_at``;
      * an application that has a recorded notification gets a decision event
        at the real ``outcome_notified_at``.

    The exact moment an application moved PENDING -> REVIEWED was never stored,
    so no REVIEWED event is fabricated. A decided application is reconstructed
    as submitted -> decision, and the timeline still reads correctly because
    each event is a real, dated transition.
    """
    Application = apps.get_model("jobs", "Application")
    ApplicationStatusEvent = apps.get_model("jobs", "ApplicationStatusEvent")

    existing_ids = set(
        ApplicationStatusEvent.objects.values_list("application_id", flat=True)
    )
    events = []
    for application in Application.objects.all().iterator():
        if application.id in existing_ids:
            continue
        events.append(
            ApplicationStatusEvent(
                application_id=application.id,
                from_status="",
                to_status="PENDING",
                note="Application submitted",
                # auto_now_add would stamp now(), so set explicitly to the
                # real submission time.
                created_at=application.applied_at,
            )
        )
        if application.outcome_notified_status in ("SUCCESSFUL", "REJECTED"):
            events.append(
                ApplicationStatusEvent(
                    application_id=application.id,
                    from_status="REVIEWED",
                    to_status=application.outcome_notified_status,
                    note="Backfilled from the recorded notification",
                    created_at=application.outcome_notified_at or application.applied_at,
                )
            )
    if events:
        ApplicationStatusEvent.objects.bulk_create(events, batch_size=500)
        print(f"[data-safety] Backfilled status history for {len(events)} event(s).")


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0021_application_status_successful"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("to_status", models.CharField(max_length=20)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="jobs.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_status_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["application", "created_at"],
                        name="jobs_applic_applica_46e9d5_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_status_history, migrations.RunPython.noop),
    ]
