# Generated by Django 5.0.3 on 2026-09-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0022_applicationstatusevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="audience",
            field=models.CharField(
                choices=[("STAFF", "Staff"), ("APPLICANT", "Applicant")],
                db_index=True,
                default="STAFF",
                max_length=20,
            ),
        ),
    ]
