"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Reading .env file
# Provide a way to override environment variables via a local .env file.
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "SECRET_KEY", default="django-insecure-fallback-key-do-not-use-in-prod^^"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = ["youth-portal-backend.onrender.com", "localhost", "127.0.0.1"]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# See core/test_runner.py: Django 5.0's test client breaks on Python 3.14 in a
# way that replaces every genuine 500 traceback with an unrelated
# AttributeError. This runner keeps the real error visible.
TEST_RUNNER = "core.test_runner.PreservingTestRunner"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "accounts",
    "jobs",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR}/db.sqlite3")
}
# Enable persistent database connections for horizontal load balancing
DATABASES["default"]["CONN_MAX_AGE"] = env.int("CONN_MAX_AGE", default=600)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Storage Configuration (Shared S3/R2 object storage readiness for horizontal scaling)
USE_S3_STORAGE = env.bool("USE_S3_STORAGE", default=False)
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", default=None)

if USE_S3_STORAGE or AWS_STORAGE_BUCKET_NAME:
    AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID", default="")
    AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY", default="")
    AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="us-east-1")
    AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL", default=None)
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "region_name": AWS_S3_REGION_NAME,
                "endpoint_url": AWS_S3_ENDPOINT_URL,
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        # "default" is used by every FileField / ImageField (media uploads).
        # It MUST be declared when overriding STORAGES or Django raises
        # InvalidStorageError on any file upload (500).
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        # "staticfiles" is used by collectstatic and WhiteNoise.
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Media files (Uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

AUTH_USER_MODEL = "accounts.User"

# Shared Session Storage (Database-backed, shared across all Gunicorn workers & instances)
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Email Backend Configuration
EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="State Department for Petroleum <noreply@petroleum.go.ke>")

# Celery / Redis Asynchronous Task Queue Configuration
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default=env("REDIS_URL", default="redis://localhost:6379/0"))
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default=env("REDIS_URL", default="redis://localhost:6379/0"))
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=True)
CELERY_TASK_EAGER_PROPAGATES = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # ── General API access ─────────────────────────────────────────────
        "anon": "30/minute",    # Anonymous browsing (vacancies list, public pages)
        "user": "200/minute",   # Authenticated general usage (reads, profile updates)

        # ── Strict per-endpoint scopes (applied via custom throttle classes) ─
        #
        # auth: login + register.  5/min = 1 attempt every 12 s per IP.
        # This is the primary defence against credential-stuffing / brute-force.
        # The original value of 500/minute made brute-force trivially achievable.
        "auth": "5/minute",

        # upload: document file uploads.  20/hour per authenticated user.
        # Prevents disk-exhaustion and bandwidth-abuse DoS attacks.
        "upload": "20/hour",

        # apply: job-application POST submissions.  10/hour per user.
        # Prevents application-flooding spam aimed at overwhelming HR.
        "apply": "10/hour",
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME":  timedelta(hours=8),   # full workday / demo session
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),    # 1-week silent refresh window
    "ROTATE_REFRESH_TOKENS": True,                  # issue a new refresh on each use
    "BLACKLIST_AFTER_ROTATION": False,              # keep simple (no blacklist table needed)
    "AUTH_HEADER_TYPES": ("Bearer",),
}

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://sdp-industrial-attachment-system.vercel.app",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://sdp-industrial-attachment-system.vercel.app",
]


# Security response-header hardening
# Note: SECURE_BROWSER_XSS_FILTER was REMOVED in Django 5.0 (the
# X-XSS-Protection header is now handled by browser CSP, not Django).
# Keeping it would generate a SystemCheck warning — removed here.
SECURE_CONTENT_TYPE_NOSNIFF = True           # Prevents MIME-sniffing attacks
X_FRAME_OPTIONS = "DENY"                     # Blocks clickjacking in iframes
SECURE_REFERRER_POLICY = "same-origin"       # No referrer leakage to third-party origins

# SameSite cookie flags — CSRF protection layer
# "Lax" on session allows top-level GET navigation (e.g. OAuth redirects).
# "Strict" on CSRF cookie blocks ALL cross-site form submissions.
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Strict"

# Global Django-level upload size guard (defence-in-depth).
# This fires BEFORE serializer validation, preventing large payloads from
# even reaching the view layer. Bound to the document module's absolute
# ceiling so the framework guard can never reject a file that the per-type
# limit in accounts/document_limits.py allows. The per-type limit (a uniform 2 MB
# for every applicant document) is enforced in DocumentSerializer; this is the
# outer hard cap, set to ABSOLUTE_MAX_BYTES, which is deliberately looser so the
# framework guard never rejects a file that the per-type limit permits.
from accounts.document_limits import ABSOLUTE_MAX_BYTES as _DOCUMENT_ABSOLUTE_MAX_BYTES

DATA_UPLOAD_MAX_MEMORY_SIZE = _DOCUMENT_ABSOLUTE_MAX_BYTES  # non-file POST body
FILE_UPLOAD_MAX_MEMORY_SIZE = _DOCUMENT_ABSOLUTE_MAX_BYTES  # file upload buffer

# Google OAuth and reCAPTCHA settings
GOOGLE_OAUTH_CLIENT_ID = env(
    "GOOGLE_OAUTH_CLIENT_ID",
    default="326667250571-20fuohrlcrds388e8avifqogc3pa7krj.apps.googleusercontent.com",
)
RECAPTCHA_SECRET_KEY = env(
    "RECAPTCHA_SECRET_KEY", default="6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
)

# Advanced System Security Hardening
SECURE_SSL_REDIRECT = env("SECURE_SSL_REDIRECT", default=False, cast=bool)
SESSION_COOKIE_SECURE = env("SECURE_COOKIES", default=False, cast=bool)
CSRF_COOKIE_SECURE = env("SECURE_COOKIES", default=False, cast=bool)
SESSION_COOKIE_HTTPONLY = True

if env("SECURE_HSTS_ENABLED", default=False, cast=bool):
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Caching Configuration
if env("REDIS_URL", default=None):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": env("REDIS_URL"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "youth-portal-cache",
        }
    }

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
